name: Build + Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'app/yarn.lock'

      - name: Install
        run: yarn install
        working-directory: ./app

      - name: Test
        run: yarn test
        working-directory: ./app

      - name: Build
        run: yarn build
        working-directory: ./app
        env:
          VITE_CLERK_PUBLISHABLE_KEY: '${{secrets.CLERK_PUBLISHABLE_KEY}}'

      - name: Configure AWS Credentials for S3 Access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_BUCKET_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: eu-west-2

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./dist/ "${{ secrets.AWS_BUCKET_PATH }}/cv-template/" --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/projects/cv-template/index.html"
        working-directory: ./app
