name: Build + Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'lambda/**'

jobs:
  build-backend:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'lambda/yarn.lock'

      - name: Install
        run: yarn install
        working-directory: ./lambda

      - name: Test Backend
        run: yarn test
        working-directory: ./lambda

      - name: Zip lambda package
        run: zip -r ../../lambda_package.zip *
        working-directory: ./lambda/dist

      - name: Configure AWS Credentials for Lambda Access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
          role-duration-seconds: 900
          aws-region: eu-west-2

      - name: Deploy lambda
        run: aws lambda update-function-code --function-name ${{ secrets.AWS_LAMBDA_NAME }} --zip-file fileb://lambda_package.zip
